### ISSUE TITLE
ACE_Spectator TODO list

### ISSUE THREAD

**Issue by esteldunedain** [acemod/ACE3#1781]
Branch: `ace_spectator`

- [x] Remove stringtable entries that aren't translated. (just leave the English lines)

- [x] Replace `isDedicated` by `!hasInterface` (https://github.com/acemod/ACE3/pull/1760#discussion_r33571672)

- [x] Do not modify viewdistance unless the user changes the slider 

- [x] Add a canInteractWithCondition isNotSpectating (or similar) to prevent the interaction menu while spectator is open. That will also block all actions binded to keypresses.

- [x] Modify the code so it modifies gear as little as possible 

- [x] `!(_x in allMapMarkers)` (https://github.com/acemod/ACE3/pull/1760#discussion_r33733952)

- [x] Make spectator mode work on missions with respawn

- [x] Add controls as CBA keybinds

SilentSpike's overhaul todo list (for 3.2.0):

- [x] Clean up the display config (use correct interface coordinate systems, remove redundant classes, etc.)
- [x] Unify interface config to make an actual display
- [x] Correctly load and unload the display
- [x] Free cam movement
- [x] Camera mode switching
- [x] Spectator map processing
- [x] Unit list processing (both compiling a flexible list of units and UX)
- [x] Functional toolbar values
- [x] Enable escape menu
- [x] Cleanup (function headers, privates, etc.)
- [x] Re-enable the compass
- [x] Togglable interface components
- [x] Settings for the following:
  - [x] Side filters
  - [x] Camera mode restrictions
  - [x] Vision mode restrictions
  - [x] Unit filters
- [x] Clock
- [x] Unit list side indication
- [x] Mouse dollying
- [x] 3D unit icons

For (3.3.0):
- [x] ~~Provide camera locking functionality~~
- [x] Prevent ace_goggles overlay
- [x] Enable zeus usage
- [x] ~~Investigate improved methods of keybind handling~~
- [x] ~~Make the values on the display toolbar interactable~~
- [x] Speed should adjust with zoom
- [x] Vertical movement speed should scale at half horizontal
- [x] **PRIORITY** The onDeath setting should be redesigned:
  - Should enable spectator state becoming a replacement for the BI death state
  - This essentially means spectator cleanly integrates into the BI respawn framework when the setting is enabled (enter on death, exit on respawn, compatible with all respawn types/templates)
  - The setting persists so that people using custom scripted respawn frameworks can disable it and integrate spectator into their own framework as desired

**Comment by SilentSpike** [comment]
>!(_x in allMapMarkers)

Since we will be making this compatible with respawn missions then the code that moves those respawn markers will need to be totally changed anyway :+1:

**Comment by SilentSpike** [comment]
I'd propose introducing a new marker `"spectator_respawn"` (or similar) to handle the spectator holding position. With some code to just move players somewhere off map if it doesn't exist.

**Comment by SilentSpike** [comment]
Oh and good idea merging this for further development, I was considering the idea myself :+1:

**Comment by SilentSpike** [comment]
Created branch `ace_spectator` for development (and updated issue).

**Comment by esteldunedain** [comment]
> I'd propose introducing a new marker "spectator_respawn" (or similar) to handle the spectator holding position. With some code to just move players somewhere off map if it doesn't exist.

Sure. We can also specify hardcoded default positions for common maps. I remember a list of default pen coordinates existed on an addon by Columdrum for ACE2; we could ask permission to use those as they are.

**Comment by SilentSpike** [comment]
Actually, looking at the calculation for the pen position now it seems fine. It just shoves players off map. I'd probably change it to just be a fixed value and cut down on some of the code.

The respawn markers being moved was presumably to avoid any weirdness with people spawning then being moved, but I'll take that code out anyway because it introduces more problems than it fixes (when respawn support is desired).

**Comment by SilentSpike** [comment]
Come to think of it, do all terrains start with (0,0) in the bottom left?

I simplified the [pen calculation](https://github.com/acemod/ACE3/commit/eeeb5434241148c68e25e18773132f7d7320e748#diff-10640250352eb6772f9c7fc7d16fd866R30) with the assumption that they do.

**Comment by esteldunedain** [comment]
> Come to think of it, do all terrains start with (0,0) in the bottom left?

No. There are maps that have an offset (a certain map from Iron Front comes to mind; it was discussed on the 10 digit gps thread).

**Comment by SilentSpike** [comment]
Hmm, that fixed default position should only be an issue in very edge case situations then. I'll leave it as is, but if anyone feels it's worth changing I have no objections :smile:

**Comment by esteldunedain** [comment]
> Hmm, that fixed default position should only be an issue in very edge case situations then

Probably. We can very well wait for gps people to solve it for us and then rip off the reward.

**Comment by voiperr** [comment]
@SilentSpike So how do we want to handle missions with proper respawn? Put a respawn timer in the corner somewhere? Is there a way of postponing the respawn menu?

R.e. gear: Ideas for preventing players from drowning without scuba gear? Maybe make a PFH to setPosASL the player floating in air (network overhead?) or attachTo a static object with an offset above the water?

**Comment by esteldunedain** [comment]
> Maybe make a PFH to setPosASL the player floating in air (network overhead?)

Yes, that would create large network overhead. 

> attachTo a static object with an offset above the water?

That'd should probably work.

Another random solution would be to actually put spectators inside bloody submarines. TBH I LOVE this idea

**Comment by SilentSpike** [comment]
@voiperr The respawn system is up to missions designers, what's needed to allow for that is just plenty of flexibility. What I'd personally consider necessary for this:
- A reliable method to mark a player as a spectator (also means we don't have to rely on checking if someone is near the pen)
- Reliable functions to load/unload spectator mode as many times as desired. Should be manually callable (we can use the ace event system for this) so that designers can set up their own scripted respawn systems

**Comment by SilentSpike** [comment]
On top of that, we could develop some configurable standard respawn systems (wave respawn, life pool, etc.) as quality of life improvements for users. Though that's me planning a little far ahead :wink:

**Comment by SilentSpike** [comment]
>Another random solution would be to actually put spectators inside bloody submarines.

Read my mind :grinning:

I've also been considering a PFH to `setOxygenRemaining 1` and figuring out a way to override the vision blurring.

**Comment by SilentSpike** [comment]
Hmm, there is another possible solution:

We could delete the player unit and cache all of it's details (so that it can be recreated upon respawn). However this might not be handled well by external scripts.

**Comment by esteldunedain** [comment]
> We could delete the player unit and cache all of it's details

That could be problematic; IDK if we can trust radio spectator modes working without the player existing.

**Comment by SilentSpike** [comment]
> without the player existing.
Would this be a problem if we switched into a virtual spectator unit?

**Comment by voiperr** [comment]
Wouldn't just assigning an public objectVar be simpler?

**Comment by SilentSpike** [comment]
For checking if a player is a spectator sure, but a virtual unit could bring some advantages (and solve multiple birds with one stone) if it wouldn't cause issues elsewhere.

I'm just spit balling though, I'm not going to change the code unless it's an immediate solution/improvement or an agreed design decision.

**Comment by SilentSpike** [comment]
So, good news everyone: `hideObjectGlobal` actually disables collision too in A3. So we technically don't even need to move spectators out of the way on respawn (which would also happen to make the rest of the code more simple).

**Comment by voiperr** [comment]
I've seen a few mission scripts use area proximity detection for whether to count players for various reasons. I still think it's prudent to throw them out of the map area.

**Comment by SilentSpike** [comment]
Hmm, that's a good point, triggers could also act unexpectedly as a result :+1:

So yeah, probably need to move them regardless.

**Comment by SilentSpike** [comment]
I've implemented a basic spectator enter/exit function in ff4fce39501ab0938f8d791b4a59d2da4a4bf1d7

Submitted PR #1783 to implement method of handling object hiding.

**Comment by SilentSpike** [comment]
RE: Drowning, we could put the units high in the air and `enableSimulation false` them?

**Comment by SilentSpike** [comment]
Well I tested that and it works, but...something went wrong with the camera script and I'm unsure if it's related

**Comment by SilentSpike** [comment]
Okay so I think because the player is being moved so far off map the game is running out of memory and crashing. Introducing optional marker `"ace_respawn_spectator"` to define an explicit position and avoid that problem.

Currently it'll just use `[0,0,0]` if the marker doesn't exist, which should avoid potential issues with triggers and things well enough for now. Once the GPS people get something done we can explicitly use the bottom corner.

**Comment by SilentSpike** [comment]
I think we should consider just removing the view distance slider.

It feels a little out of place (and redundant) to me having it in the spectator interface.

**Comment by voiperr** [comment]
Streaming/screenshots/etc would benefit from it. I'm making it optional via module.

**Comment by esteldunedain** [comment]
> Streaming/screenshots/etc would benefit from it. I'm making it optional via module.

Keep in mind that we have a viewdistance module already, and the plan is to include keybinds to up/down the viewdistance at any given time (those keybinds are not added yet). Maybe that could serve the same purpose here.

**Comment by voiperr** [comment]
Aren't there plans for VD restriction, though? Maybe some mission makers would want it so spectators can see further than players could.

**Comment by esteldunedain** [comment]
> Aren't there plans for VD restriction, though? 

There's already a configurable (optional) viewdistance restriction. We could add independent restriction distances for playing vs spectating players on that same module.

**Comment by voiperr** [comment]
VD done:
https://github.com/acemod/ACE3/pull/1789

**Comment by voiperr** [comment]
Oops, still a few left (I blame notepad++): https://github.com/acemod/ACE3/pull/1791

**Comment by voiperr** [comment]
Keybindssssssss: https://github.com/acemod/ACE3/pull/1794

**Comment by SilentSpike** [comment]
All that's immediately left to do is get the enter/exit system to a reliable state and do some cleanup.

There are further enhancements to be made, but we can work on those after this.

**Comment by esteldunedain** [comment]
Yup. Keep in mind that entering/exiting spec mode needs to bind/unbind keys now too

**Comment by SilentSpike** [comment]
:+1: Good call, I'm gonna clean that stuff up in a bit

**Comment by SilentSpike** [comment]
@voiperr May I ask what purpose the "killed" EH serves exactly?

**Comment by voiperr** [comment]
Local EH applied to remote units. As soon as they die, updates the tracking array, exits POV if inside that unit, and provides death message.

**Comment by SilentSpike** [comment]
I mean the one in postInit :)

**Comment by voiperr** [comment]
Handles when player initially dies, then applies in case player somehow dies in pen (unlikely) or hits respawn button in menu. No reason it can't be a function. :wink:

**Comment by SilentSpike** [comment]
Isn't it redundant though? All of those things seem to be handled on respawn as far as I can tell

**Comment by voiperr** [comment]
The hearing update and fadeout, the fade to black, all need to start on player death (assuming we're keeping those (I think we should keep the sound one, at least)). Group joining could go to respawn.

**Comment by SilentSpike** [comment]
- I removed the sound and black fade on death (they don't really serve a purpose). The black fade also kept breaking and becoming permanent - I couldn't figure out why.
- Unit side and group are cached upon death to support "respawning" (unit side was previously cached in postInit, but that won't work in missions where units change side). It seems that the group either isn't cached correctly (and becomes `grpNull`) or BI have changed the game again to delete empty groups (they've flip-flopped on this a bunch of times). Either way, if the group is `null` is just creates a new one on "respawn" so nothing's changes there. It's important not to create groups en mass because we don't want to contribute to the group limit any more than necessary
- Introduced `handleRespawn` and `handleKilled` functions for organisation purposes (`handleRespawn` is so that we aren't using a public function - `setSpectator` - as part of the base framework itself).

**Comment by SilentSpike** [comment]
My todo for tomorow:
- Clean up camera/controls code
- Finalize "respawning" support. Possible ideas for this:
  - We could `forceRespawn` the player and let the game handle proper respawn procedure. This would have the benefit of supporting respawn templates by default and processing the correct event handlers. The downside would be that 2 deaths would take place which might produce unforeseen problems for external code (including mission designers) - granted, the current spectator system might produce unforeseen problems for external code anyway.

**Comment by SilentSpike** [comment]
Taken care of some respawn stuff, haven't pushed as I'm in the process of cleaning up the display configs.

**Comment by SilentSpike** [comment]
ace_spectator now _essentially_ supports respawn. The framework is there, but I plan to add more ease of use functionality into it.

First I want to clean up the interface code/config though. Already made good progress on the config but it's not quite in its final form.

**Comment by SilentSpike** [comment]
Oh, there are also some errors present in the interface code I'll have to take a look into.

**Comment by SilentSpike** [comment]
Considering stripping out the time acceleration functionality as it seems a little like feature creep, any thoughts?

It's only really useful in single player, but then you'd only enter the spectator mode via script in SP anyway as either a result of:
1. The mission designer - who presumably wouldn't want you messing with time acceleration.
2. Yourself - who presumably could execute the necessary commands manually as desired.

Is our design intent for ace_spectator to be multiplayer-centric?

**Comment by esteldunedain** [comment]
I agree.

**Comment by SilentSpike** [comment]
So I'm currently in the process of overhauling all the interface and camera code to make it cleaner and functionally improved. My todo list:

- [x] Unify interface config to make an actual display
- [x] Correctly load and unload the display
- [x] Free cam movement
- [ ] Camera mode switching
- [ ] Spectator map processing
- [ ] Unit list processing (both compiling a flexible list of units and UX)
- [ ] Make the values on the display toolbar interactable

**Comment by SilentSpike** [comment]
An interesting design challenge presents itself. Camera view management is almost done, but I first need to do the unit list handling.

My goal is to use a global array exposed to a public function to store the spectatable units. However I need to be able to translate between the unit in the array and the "unit" stored in the dialog tree.

Going to test some _forEachIndex stuff and see how that works out

**Comment by MrSanchez** [comment]
Hey if you don't mind me asking;

How similar will this spectator screen be to the (popular) ACE2 one?

Kind regards,
Sanchez

**Comment by SilentSpike** [comment]
@MrSanchez I don't recall if I ever used (let alone knew about) the ACE2 one :stuck_out_tongue_closed_eyes:

**Comment by MrSanchez** [comment]
I'd like that.

I'd like to say that I used the ACE2 'dead' spectator screen longer than I actually played in operations, but that would imply that I suck at the game xD

The ACE2 spectator screen was a modified version of Kegety's spectator script, totally rewritten but interface kept the same. It had user-accessible variables that allowed you to modify it's features.
such as 
ace_sys_spectator_playable_only=true;
ace_sys_spectator_no_butterfly_mode=true;
ace_sys_spectator_CheckDist = 100;

There was also a variable (ace_sys_wounds_withSpect=true;) that allowed for the spectator script to be triggered once you'd go into Poor Man's Revive mode..I hardly used that though.

A lot of the current A3 spectator scripts do not allow for such easy control of certain features of the script without having to modify the actual script manually.

Anyway, looking forward to some of those screenshots ^^

Kind regards,
Sanchez

**Comment by SilentSpike** [comment]
Ah, I looked up kegety's script and found this: http://www.armaholic.com/datas/users/spectator_4.jpg

**Comment by MrSanchez** [comment]
"An array of the units that can be spectated exposed to some public functions (for absolute control)"
This means I will be able to exclude certain units from being spectated ye? That's actually a feature I've used the most yet forgot to mention in my previous post :P

If your script allows to spectate using NVG/TI, an option to force-disable that would be splendid. I played a vietnam-inspired operation where I allowed no usage of NVG or TI in the op, and would've preferred it if our spectator system didn't have that either (so that those who spectate can be surprised by bush-enemies shooting at friendlies too :) )

Oh and I assume that your 'free' mode won't have the exact same controls as BIS' 'camera.sqs' aka bis_fnc_cameraOld system, any chance you can incorporate that as an additional feature? Maybe on a keybind? I like it because it uses the Buldozer movement controls and with 'Delete' you can turn on&off smoothing/floating mode, and most importantly, it works with my Xbox360 controller that I use to record cinematic events with.

That's all I can come up with now ;)

Kind regards,
Sanchez

**Comment by SilentSpike** [comment]
NVG/TI restrictions are definitely on the todo list.

As for controls, they're really a PITA to work with so we'll see how feasible that is once I've fleshed them out better. :+1:

**Comment by MrSanchez** [comment]
Ah okay, I was just on about triggering the function bis_fnc_cameraOld by a keybind while spectating, and being able to press a keybind again to turn it off and switch to the normal spectating.
The camera old function has it's own controls that you wouldn't have to touch or anything.

Kind regards,
Sanchez

**Comment by SilentSpike** [comment]
Ah, I see what you mean. Well, I'd probably consider that feature creep since anyone who wants to do so can just do that manually.

However, that's not to say I rule it out completely.

**Comment by SilentSpike** [comment]
Here's a WIP preview of what the interface could look like:

![IMG](http://i.imgur.com/LpFJ2il.jpg)

It's still undergoing change (and isn't functionally complete), but feedback is always welcome. I also need to fix the goggles overlay appearing.

**Comment by MrSanchez** [comment]
I like it...What is the point of the crosshair though?

**Comment by SilentSpike** [comment]
It's holdover from the initial integration of @voiperr's work, he could probably tell you more.

**Comment by SilentSpike** [comment]
More screenshots:

Third person:
![Third Person](http://i.imgur.com/UcdB2eV.jpg)
First person:
![First Person](http://i.imgur.com/K0Qu8b3.jpg)
Map view:
![Map View](http://i.imgur.com/558ghXN.jpg)

**Comment by SilentSpike** [comment]
Oh and don't worry about the crosshair. It'll be gone from unit views and probably also free cam (I would like to enable camera attachment functionality, so I'll try to think of an alternative).

**Comment by MrSanchez** [comment]
Looking good....If the first version of this spectator script isn't going to include bis_fnc_cameraOld switch, it might be a good idea to make that crosshair toggle-able. Just so that there is an uninterupted freecam view.

Kind regards,
Sanchez

**Comment by SilentSpike** [comment]
Oh yeah, it'll either be removed entirely or togglable :+1:

I'll make the toolbar toggleable also.

**Comment by SilentSpike** [comment]
Some more previews of the latest changes:

Third person, all UI elements visible (excluding map):
![](http://i.imgur.com/2cpI366.jpg)

First person, standard UI elements visible:
![](http://i.imgur.com/7L0za7z.jpg)

Free cam, only compass visible:
![](http://i.imgur.com/JXCKARL.jpg)

**Comment by MrSanchez** [comment]
Lookin good..keep up the good work.

**Comment by SilentSpike** [comment]
@esteldunedain I've taken a quick look at ace_goggles to see how I can stop the overlay while the spectator interface is open. I notice it's checking `EFUNC(common,isFeatureCameraActive)`

Just want to double check that it would be suitable to add a check for the spectator camera into that function? (ace_goggles is currently the only thing using it)

**Comment by SilentSpike** [comment]
Could use some help with the 3D unit icons, I've pushed the code and it's theoretically functional. For some reason though the unit icons aren't being drawn.

`FUNC(handleIcons)` is where you can find the relevant code if anyone wants to take a look. What I've tried so far:
- Using `nearEntities` (produces more overhead - also didn't fix it)
- Checking if it's because of `cameraEffectEnableHUD false` in `FUNC(transitionCamera)`
- Using `GVAR(camPos)` as the first `distanceSqr` argument in case it was some weirdness with the camera object

Going to take a break and then come back to do some debugging

**Comment by SilentSpike** [comment]
Escape menu done, just need to debug 3d unit icons and ace_spectator framework is ready for initial release.

**Comment by SilentSpike** [comment]
Just to document this design decision (slack log):

>Hmm, once again I'm running into non-flexible BI systems. I can either:
- Override their respawn templates at the config level
- Override their respawn templates at the function level
- Override their respawn templates using code running in parallel
- Override their respawn framework
>
>Can't figure out which is the least intrusive. I think function level might be
>
>It'd mean hacking their functions up a little bit, but that means their stuff is still being ran as expected by external observers
>
>While still being able to elegantly override the parts that should now be setting-dependant

**Comment by SilentSpike** [comment]
It seems I've hit a crossroad:

![](http://i.imgur.com/CE9BsAK.jpg)

The respawn display there is handled by engine magic and the only way to disable it is via an entry in description.ext. This means that using edited BI respawn templates to support an ace setting to simply enable/disable the spectator system isn't ideal.

The main advantages that approach brings is that it can be tweaked instantly via the settings framework and is backwards compatible with missions designed prior to ace. However, if a description.ext edit is required anyway then both of those points are nullified.

So instead of using a setting, I propose we add our own spectator respawn template to allow mission designers to enable the system that way. This changes a few things:
- If someone wants to enable/disable the system then they'd need to edit the mission files (or design their own respawn framework - which many communities do).
- Custom respawn frameworks remain fully supported via functions.
- It actually makes ace_spectator entirely non intrusive and so compatibility is not a concern any more - that responsibility is shifted to the mission designer (to use a working combination of respawn templates/code).
- It also actually brings some advantages because the BI respawn system has some nice built in functionality (for example you could give only 1 side spectator on death and another side infinite wave respawns if you wanted).

**Comment by SilentSpike** [comment]
Some feedback from user testing:
- Add text chat for spectators
- Smooth camera movement based on height
- Add system to public API to kill the spectator dialog and reopen for external systems to use
- Compass is pixelated?

**Comment by jonpas** [comment]
> Add text chat for spectators

Put all spectators in same group? Or create a new channel (if that works)?

**Comment by SilentSpike** [comment]
I'm thinking create a new channel, though the scripting logistics of that remain to be seen

**Comment by SilentSpike** [comment]
Closing as spectator is ready for 3.3.0.

Future improvements can be handled in new issues
