### ISSUE TITLE
TODO list for trenches

### ISSUE THREAD

**Issue by nicolasbadano** [acemod/ACE3#3263]
The following things could be improved on ace_trenches:
- [ ] Either replace texture for something that better fits all terrain (e.g. soil) or provide different variants
- [ ] Improve UV coordinates for both models
- [ ] Create LODs
- [ ] Better animations?
- [x] Remove grass behind the trench (#3612)
- [x] Possibly require various interactions for the trench to grow to full height (#3612)
- [ ] Allow collaboration of multiple players.

**Comment by PhillyJoker** [comment]
How about providing an option to remove them?

**Comment by SzwedzikPL** [comment]
@PhillyJoker take a look at https://github.com/acemod/ACE3/pull/3612 :)

**Comment by PhillyJoker** [comment]
Ah, excellent. Was wondering if i was going to have to waste time scripting it... Thanks.

**Comment by nomisum** [comment]
More suggestions: 
* Make build time a lot longer or adjustable.
* ÄCheck ground (currently building on streets is possible)

Compared to sandbags trenches are very imba currently. I'd propose a similar building system for sandbag object compositions (already experimented with that), but thats going offtopic.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
