### ISSUE TITLE
Todo list for Overheating

### ISSUE THREAD

**Issue by nicolasbadano** [acemod/ACE3#3373]
Ready for 3.6.0:
- [x] Track temperature of spare barrels (#3438)

For 3.7.0+:
- [ ] Enable overheating for static weapons.
- [ ] Make silencers (but not suppresors) break when shot at high temperature.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
