### ISSUE TITLE
TODO List: Mortars

### ISSUE THREAD

**Issue by gienkov** [acemod/ACE3#3490]
_Edited by Ed_:
- [ ] Add a mode in which rounds are auto fired as soon as dropped. [Video showing both modes for the M224](https://www.youtube.com/watch?v=DfkOeHQXAaM)
- [ ] Make it possible to switch between "Fire on drop" and "Fire on trigger" modes.
- [ ] Add support for third party mortars (CUP)
- [ ] Mortar could make metal friction sound while shell moves through barrel, and fire split second after that automatically - like in reality does
- [ ] And you could prepare charge on them what is more realistic
- [ ] Make individual shells carriable around

**Comment by Armilio** [comment]
First, it would be good some more documentations about the mortar with "air resistance" activated. Especially about air density that it's still unclear how works and what kind of calculation needs.

**Comment by Glowbal** [comment]
Pinging @NouberNou since he mentioned something about being able to port ACE2 mortar functionality now he has the proper models.

**Comment by austinjames314** [comment]
@Armilio It was working fine when you posted in June last year, and it's still working fine for me. Try using my calculator spreadsheet, based purely on the in-game tables: https://drive.google.com/file/d/0BxfgbiRB-sRrUkd4dVdOeVZ4alU/view?usp=sharing
Note, it only works properly in Libre Office, with macros turned on.

**Comment by Armilio** [comment]
@austinjames314 As you wrote you months ago (maybe, i don't remember) that method did work well as approsimation with near-average air density, but with high or low density not. Anyway, i will try again with your calculator, thanks.

**Comment by headedhorseman101** [comment]
If mortar shells are allowed to be carried around, can the character have a faster limit than a slow walk, such as the binoculars running pace. The cartridges for the 60mm M224 have weights that don't exceed 4 lbs Having the soldier constantly walk while only carrying 4 lbs would be a little excessive imo.

**Comment by Khaosmatic** [comment]
Could they not also be inventory items as well similar to the static weapon ammo boxes back on ACE2 or even the way the current 3CB static weapons work?

**Comment by austinjames314** [comment]
Just dropping in to the devs know: the 3CB BAF weapons mod has implemented almost all of these features. They don't have prepping of charges as such, but they do have 81mm ammo as inventory items, and they had fire on drop.

You may be interested to know they had issues with fire-on-drop: apparently because they used a function call to fire the mortar, instead of the player firing it themselves, the rounds would always get fired at default elevation. Details here: http://3commandobrigade.com/viewtopic.php?f=57&t=4583&start=120

Just a potential pitfall I thought I'd mention.

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
