### ISSUE TITLE
TODO list for tagging

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#3696]
Ready for 3.6.0:
- [x] Align tags vertically in non-horizontal surfaces

For 3.7.0+:
- [x] Scripted API for custom tags, possibly like this #4146 
  ```
  ["Circle", "path\to\circle.paa"] call ace_tagging_fnc_createCustomTag
  ```
- [x] Custom tags by config documentation #4150 
- [x] Scripted API documentation #4150 
- [x] ~~Make checkTaggable public~~ not necessary

**Comment by ColdEvul** [comment]
Reference from the [help chat at slack](https://ace3public.slack.com/archives/help/p1461172389000286)
add possibility to set rotation as a param so you don't need to write a entire system for custom tagging when text is involved. :)

http://images.akamai.steamusercontent.com/ugc/278471138304886827/7EB996E32A76021DDA074369568E9A2E031BA4BA/
