### ISSUE TITLE
TODO Replace execRemoteFnc with events

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#3763]
`ace_common_fnc_execRemoteFnc` is deprecated and will be removed in 3.7.0. Should get rid of all occurrences in ACE3's code for 3.6.0.

**Comment by commy2** [comment]
- [ ] addons/rearm/functions/fnc_rearmEntireVehicleSuccess.sqf 
- [ ] addons/repair/functions/fnc_useItem.sqf 
- [ ] addons/common/functions/fnc_sendRequest.sqf 
- [ ] addons/respawn/functions/fnc_handleKilled.sqf 
- [ ] addons/rearm/functions/fnc_rearmSuccess.sqf 
- [ ] addons/common/functions/fnc_onAnswerRequest.sqf 
- [ ] addons/rearm/functions/fnc_pickUpAmmo.sqf 
- [ ] addons/switchunits/functions/fnc_switchUnit.sqf 
- [ ] addons/spectator/functions/fnc_respawnTemplate.sqf 
- [ ] addons/explosives/functions/fnc_startDefuse.sqf 
- [ ] addons/spectator/functions/fnc_stageSpectator.sqf 

mine:
- [ ] addons/common/functions/fnc_serverLog.sqf 
- [ ] addons/common/scripts/checkVersionNumber.sqf 
- [ ] addons/common/functions/fnc_execPersistentFnc.sqf 
- [ ] addons/common/functions/fnc_checkPBOs.sqf 
- [ ] addons/common/XEH_PREP.hpp 
- [ ] addons/common/XEH_postInit.sqf

**Comment by Glowbal** [comment]
`fnc_onAnswerRequest` is part of a legacy framework that came over with CSE - if we ever want to make use of it, we should rewrite it in full. We might be better off to simply deprecate it and get rid of it entirely. Same story with `fnc_sendRequest`.

**Comment by jonpas** [comment]
Also `ace_common_fnc_remoteFnc` needs to be abolished.

**Comment by jonpas** [comment]
@Glowbal `fnc_sendRequest` is marked as public so we can't just remove it without having an alternative, I changed it to events for now.
