### ISSUE TITLE
TODO list for Advanced Throwing

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#4281]
- [ ] Add keybind for priming (ignore if middle mouse button action is binded)
- [ ] Add setting to follow head direction or not (body direction)
- [ ] Improve throwable rendering position (mainly moves too much while looking up/down)
- [ ] Improve in-vehicle `canThrow` check to make throwing from non-FFV seats work well (required for below)
- [ ] Allow throwing from inside vehicles (eg. copilot and back seats of little bird) - `lineIntersectsSurfaces`
- [ ] Fix and allow throwing from ladder (with less power) - needs positioning fixes on throw

**Comment by McDiod** [comment]
I'll just add this here instead of making a separate issue:
You are able to pick up cooked throwables while other players are carrying them. Throwable will then flicker back and forth between you and the other player.

**Comment by jonpas** [comment]
@McDiod Will be fixed in #4313 hopefully. Very nice catch, thanks for the report!

**Comment by jameslkingsley** [comment]
I thought that was a feature, it's actually pretty good. If you're stacking up on a door and the point-man doesn't have a grenade, he can turn around, pickup a grenade straight from the hands of the guy behind him and then chuck it in.

**Comment by jonpas** [comment]
It is a feature, I managed to add proper Locality support for it. :)

**Comment by jameslkingsley** [comment]
I think it would also be good to have a keybind to pickup grenades. I'm not entirely sure how it would work, but there would probably need to be a threshold. Press keybind, get all grenades in 1m radius, limit to ones visible in screen space, convert positions to screen coords and check their 2D distance to center.

**Comment by jonpas** [comment]
I like how it is, hard to do, it should be hard, I don't want people picking up grenades with ease. And as it is currently it simulated kind of real life picking up, makes much more sense to me, keybinds are instant.

**Comment by john681611** [comment]
I agree the key bind is too simple but I think the interaction zone may be too small. This should aid picking up and even catching which should be possible if prepared. Remember interactions in Arma are going to be nowhere as good as IRL.

Silly side note throwing unarmed grenades and mags would be nice for squads under fire and games of catch :D

**Comment by jonpas** [comment]
This is unlikely to be happening after 8 years. If any of it would be that wanted, I am sure we would get more requests for it.
