### ISSUE TITLE
TODO list: Zeus improvements

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#4454]
Done:
 - [x] Garrison and un-garrison module. 
 - [x] NVG toggle module. (possible review needed)
 - [x] Flashlight toggle module. (possible review needed)

TODO:
 - [ ] Artillery module(s).
 - [ ] Composition system (either a bunch of modules or a menu called via a shortcut) to manage personal compositions, and possibly share them.
 - [ ] Add full arsenal to object.
 - [ ] Damage unit (based on basic or advanced, can use the code I already made for https://github.com/alganthe/ganthe_ACE3medical_vr)
 - [ ] Fully heal unit module.
 - [ ] Destroy X random building in Y radius module.
 - [ ] Open/Close X doors in Y radius.
 - [ ] Create minefield module.
 - [ ] Earthquake module.
 - [ ] Advanced weather module (need to check all the commands and the syncing behind them)

branch: https://github.com/alganthe/ACE3ganthe/tree/zeus_improvement
Feel free to post suggestions or requests

**Comment by commy2** [comment]
why don't you make this a PR?

**Comment by alganthe** [comment]
it's not even near completion, it'll be better to wait until I get closer to finishing what I intend to do then PR, at least review wise.

**Comment by PabstMirror** [comment]
See Changes:
https://github.com/acemod/ACE3/compare/master...alganthe:zeus_improvement

**Comment by 654wak654** [comment]
- Add/Remove all objects in X radius to curator.
- Change weather.
- Damage unit.
- Destroy X random buildings in Y radius.
- Open/Close X doors in Y radius.
- Change time acceleration.
- [Earthquake](https://community.bistudio.com/wiki/BIS_fnc_earthquake).
- [Create minefield](http://i.imgur.com/jPRBj5o.png).

No dialog needed:
- Add full arsenal to object.
- Fully heal unit.

**Comment by alganthe** [comment]
time acceleration and weather are already in game and synced.
For the rest i'll add them.

**Comment by kripto202** [comment]
why have this when ares can do most of this?

**Comment by jonpas** [comment]
Because Ares is not getting updated. And this is a much better framework.

**Comment by 654wak654** [comment]
Didn't know time acc was vanilla ¯\\_(ツ)_/¯ 

**About weather, here is the vanilla module:**
![vanilla](https://cloud.githubusercontent.com/assets/8149303/18792359/dd628dd2-81be-11e6-8801-e9264145266e.png)

**And here is the Ares module:**
![ares](https://cloud.githubusercontent.com/assets/8149303/18792363/e2b607e6-81be-11e6-8637-0e289c25b664.png)

**Comment by kripto202** [comment]
> Because Ares is not getting updated. And this is a much better framework.

have you looked at Ares Achilles? I'm just saying that a lot of the features are already in that mod

**Comment by SilentSpike** [comment]
I'm afraid this issue doesn't pertain to the `acemod/ACE3` repository and would be more suitable as either an issue on your own fork's tracker or a pull request.

I'd suggest submitting a pull request as feedback on proposed changes/additions would be easier to give and centralised to one location. Even WIP changes are suitable for PR and can be tagged as such. I hope you understand we can't allow anybody who forks ace to start using our tracker for their own purposes.
