### ISSUE TITLE
Medical Rewrite Private Beta Milestone

### ISSUE THREAD

**Issue by ViperMaul** [acemod/ACE3#4829]
From our Medical Rewrite mid-month meeting:

- [x] Refactoring of the vitals loop (medication loop, heart rate, blood pressure, ...)
- [x] Performance optimizations (medication loop)
- Network synchronization (blood bag visualization) -> #5098
- [x] PP effects for pain, bloodloss, unconsciousness (https://github.com/acemod/ACE3/pull/4754) 
- [x] Develop Workaround for Handled Damage Issue 45aa80 (#4828)
- [x] Internal MP testing on True Dedicated Server

**Comment by jonpas** [comment]
All done except #5098, which will be post-release.
