### ISSUE TITLE
1.82 Refinement ToDo

### ISSUE THREAD

**Issue by PabstMirror** [acemod/ACE3#6248]
Taken from #6201
- [ ] Realistic names for new tanks/weapons? 
- [ ] Probably remove vanilla fire mode (f key) for javelin/nlaw
- [ ] Look into using submunition changes `Mo_NLAW_AT_warhead`
- [ ] Fix realistic names for expansion LSV (open top car)
- [x] Fix track repair (getAllHitPointsDamage)
- [ ] Reduce overpressure on cannon launched missiles

**Comment by Snak3Doc** [comment]
Possibly remove the crazy OP top down attack mode for the rhino's atgm, or change it so it's not just, point click and forget on anything you have LOS on.

**Comment by john681611** [comment]
Fairly sure top-down modes are rather common for AT now don't see why it should be removed because its OP.

**Comment by Snak3Doc** [comment]
Im sure it can do something similar, my point is it's too easy, not sure if its laser, IR or GPS guided IRL but the vanilla system is magic and ace has systems for both IR and laser ie, javelin or Hellfire/Lasercode.

**Comment by xrufix** [comment]
Regarding cannon launched missiles:

I watched some videos, e.g. [this](https://youtu.be/KaDZw1DuMGk?t=86) or [this](https://www.youtube.com/watch?v=p0egn8-qpT0), and to me it doesn't seem to have lower overpressure than other cannon munitions.

**Comment by Drofseh** [comment]
> Regarding cannon launched missiles:
I watched some videos, e.g. this or this, and to me it doesn't seem to have lower overpressure than other cannon munitions.

I think it must really depend on the weapon and platform.

These ones seem to have very little overpressure, especially the LAHAT:
[Refleks](https://www.youtube.com/watch?v=MC8e5KT8IDg)
[Kombat](https://www.youtube.com/watch?v=6RKnJSOgksw&feature=youtu.be&t=3m6s)
[LAHAT](https://www.youtube.com/watch?v=uECU83_XiKY&feature=youtu.be&t=1m14s)

**Comment by Mike-MF** [comment]
Closing due to age, inactivity or already solved. May be re-opened if the issue is still present, even better just open a new up-to-date Issue.
