### ISSUE TITLE
TODO armake

### ISSUE THREAD

**Issue by jonpas** [acemod/ACE3#6363]
Split from #3747.

- [ ] Rework `Makefile` to standard release/publish procedure (ref. https://github.com/CBATeam/CBA_A3/pull/730#issuecomment-411018642)
- [ ] Fix `make.ps1` on Windows 8 (ref. https://github.com/acemod/ACE3/pull/3747#discussion_r192170181)
  - [ ] Add version header entry to `make.ps1`
- [ ] Adapt armake to launchable mod folder optionals

**Comment by jonpas** [comment]
Superseded by HEMTT #6900.
