### ISSUE TITLE
Medical Rewrite - TODO

### ISSUE THREAD

**Issue by alganthe** [acemod/ACE3#6913]
### Needs Testing:
- [x] **Needs testing**. Add / fix vitals conditions for unconsciousness, currently only damage results in it.

### To Do (Unclaimed):
- [ ]  **?** Unconsciousness mutes sounds in zeus (sound is not reset when entering curator after going unconscious, see [here](https://github.com/acemod/ACE3/blob/master/addons/medical_feedback/XEH_postInit.sqf#L49))
- [ ] **Medium**.  Remove bleedout event in favor of fatal injury event (remove from state machine, too)
- [ ] **Discussion**. More heavy injuries increase condition of the next one being fatal ("stacked damage")
- [ ] **?** Fix people running with 4 tourniquets without consequences.

### Think about:
- [ ] **After Release**. Look into reducing target events with treatments. Reference: https://github.com/acemod/ACE3/pull/6925#issuecomment-480618638
- [ ] Medical Blood - https://github.com/acemod/ACE3/pull/7069#discussion_r297099846 - extra setPos?
- [ ] Should do a final pass once the above are merged and settings are finalized.

### Fixed:
- [x] **Trivial**. Pain / color grading effects are too tame. (#7215)
- [x] Look into AI stop shooting setting (ref #7074) old setting `delayUnconCaptive`
- [x] **?** Bandages and medication are twice as heavy as previous medical (0.09kg vs 0.05kg) (#7200)
- [x] **trivial** Increase carry pickup speed #7216
- [x] Remove Atropine (please) #7212 
- [x] **Critical**. Vitals loop should run at cardiac arrest with a minimum heart rate of ~20 to simulate gravity effects (bleeding, blood bags) - affects CPR (whoever wants to claim this, just work on top of #7013) PR #7060
- [x] **Medium**. Sort medical settings into appropriate subcategories. (PR #7057)
    - AI subcategory will be corrected by #6902 
    - A lot of settings, including GUI, will be corrected by #6933 
- [x] **Medium**. Fix surgical kit treatment condition. (#6916, #7044) 
- [x] Limping Todo: Issue #6940 - PR #7045
- [x] AI does not stop shooting unconscious players (#7074)
- [x] **Critical**. Medications have no effect (including IVs) after #6933 (PR #7048)
- [x] **Critical**. Fix unconscious UI effects in copilot camera / turrets. (#7003)
- [x]  Fix patient unloading failing to put the patient back in unconscious anim on dedicated
- [x] Fix unconscious person being able to access the medical menu. (#6915)
- [x] Morphine isn't removed after usage through a remote unit.
- [x] Add back heal hitpoints setting (under a different name).
- [x] **Critical**. Add lower limit on bandaging speed to avoid insane animation speeds.
    - May need to further look at adjusting bandaging times specifically?
- [x] **Critical**. Fix bleeding rate. (#7010)
    - Should be fixed, could use play-testing.
- [x] **Critical**.  HR skyrockets between 4 - 5L of blood (#7010)
    - Quote from silentspike "Yeah, BP influences HR, HR influences CO, CO influences BP"
- [x] **Low** Fix the unconscious toggle zeus module not being permanent. (PR #7030)

**Comment by SilentSpike** [comment]
For heal hitpoints, I suggest naming it along the lines of exactly what it does:

"Bandages heal damage"

**Comment by Katalam** [comment]
EDEN Atrribute have to be moved up again.
https://i.gyazo.com/cda395b0d64a542b4285f4dfabc2942f.png

**Comment by TheMagnetar** [comment]
I have not been able to reproduce the Morphine bug. Both morphine and epinephrine got removed.

**Comment by alganthe** [comment]
@TheMagnetar dedicated environment, shot myself with a remote controlled unit.
Gave myself a morphine in the left arm while the unit had a morphine stick in it's uniform inventory and I had none, the stick didn't disappear.

**Comment by zharf** [comment]
Unconscious person can access medical menu and bandage themselves

**Comment by SilentSpike** [comment]
Heal hitpoints setting related to #6458 where some useful previous discussion has taken place. Apparently my opinion on the setting name hasn't changed since then 😆

**Comment by Katalam** [comment]
I'm not sure if this is a bug, but when you got a patient. You will get the button for CPR, but this will immediately stop if the target isn't in cardiac arrest. For bandaging and stitching we got the button only when it's needed. Maybe do it here too.

https://github.com/acemod/ACE3/blob/55a7d5343723c5cd44cd339183c29d27d8be72d1/addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp#L249

https://github.com/acemod/ACE3/blob/55a7d5343723c5cd44cd339183c29d27d8be72d1/addons/medical_treatment/functions/fnc_treatmentCPR_failure.sqf#L18

These are different conditions. Maybe merge them to one. Because clicking the button and immediately stop the action isn't nice.

**Comment by Katalam** [comment]
Can we open the discuss about #5293 again? I mean atropine should really raise the hr

**Comment by Zakant** [comment]
If I rember correctly I was the one adding the possibility to do cpr if the target is not in cardiac arrest. It was by design to make sure people check whether or not the target needs cpr. My test group quickly found out that the cpr button is a reliable option to tell the status of a person. Maybe introducing an setting would be an option. If not I would vote to be able to do cpr even if the target is not in cardiac arrest.

**Comment by Katalam** [comment]
> If not I would vote to be able to do cpr even if the target is not in cardiac arrest.

That would be nice

**Comment by SilentSpike** [comment]
I'd say make CPR always an option if patient isn't responsive (as you'd never accidentally do it to someone who is) and have it cause damage to the torso, then if you do it on someone who doesn't need it it's counterproductive - incentivising status checks first.

**Comment by Katalam** [comment]
You will never deal damage with CPR but some rip breaks if you do it too long. This is normal even for patients who are in the need to get CPR. In real life you can even do CPR on reponsive persons (Normally it comes with a lot of pain)

**Comment by severgun** [comment]
> In real life you can even do CPR on reponsive persons (Normally it comes with a lot of pain)
That is why you will get hit in face first.
> I mean atropine should really raise the hr
Adenosine and Atropine should be removed from game. There is no use for them. There is no poisoning implemented.

**Comment by SilentSpike** [comment]
By damage I was thinking along the lines of bruising.

To be honest, back when I had more time, I wanted to overhaul how CPR works and just make it a continuous action until disengaged which would intermittently perform a status check for you.

**Comment by pognivet** [comment]
I suggest being able to set how long a unit remains unconscious for after being wounded. Kind of stupid for someone to be unconscious for 25 seconds. Never seen that in my life as a EMT.

**Comment by SilentSpike** [comment]
Should note as discussed in slack:
> HR skyrockets between 4 - 5L of blood

This is due to the updateHeartRate function in vitals and it's unclear if intentional (we really need to be commenting *why* code is doing what it's doing).

https://github.com/acemod/ACE3/blob/9c55c36d27e15e06b2c2aff86fb1aede30bb5891/addons/medical_vitals/functions/fnc_updateHeartRate.sqf#L34-L42

The first condition is false so the targetBP stays at 107 and the second condition is true so the HR keeps increasing.

**Comment by LachlanSneddon** [comment]
> HR skyrockets between 4 - 5L of blood

I think this is the implementation of #1733, although the HR change is significantly different with a HR of 220 being reached just before Class 4 Hemorrhage.

> Trivial. Pain / color grading effects are too tame. 

Although borderline settings bloat, making this a setting that users can define could be an easier alternative

![image](https://user-images.githubusercontent.com/38343770/61506373-f90edc00-aa35-11e9-88ab-505f4c27c956.png)

**Comment by PabstMirror** [comment]
tag older design issue https://github.com/acemod/ACE3/issues/3134

**Comment by kymckay** [comment]
I think this issue is outdated and resolved. Any specific points of discussion we want to track should be opened as fresh issues for tracking.
