### ISSUE TITLE
Medical Rewrite: Extension & wound assignment TODO

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#6939]
- [x] Disable extension completely for now
- [x] Add handling of fractures (`causeFracture` flag in wound config)
- [ ] Test how far wound assignment can be optimized, benchmark, check if extension is necessary

**Comment by dedmen** [comment]
Note for re-enabling extension later on.
If we just try to call it once at preStart so that battleye sees it. They will auto-whitelist the extension if enough people try to load it.
So we could add it one-release before we actually put it to use to make sure it get's whitelisted.

Don't know how it was done in the past, messaging BE asking to whitelist it?

**Comment by jonpas** [comment]
> Don't know how it was done in the past, messaging BE asking to whitelist it?

Correct.

**Comment by dedmen** [comment]
I heard mostly bad things about BE support recently. So might be worth keeping the other option in mind as a fallback.

**Comment by TheMagnetar** [comment]
>If we just try to call it once at preStart so that battleye sees it. They will auto-whitelist the extension if enough people try to load it.

That sounds... dangerous?!

**Comment by BaerMitUmlaut** [comment]
I wouldn't worry about whitelisting, it's automated.

**Comment by LinkIsGrim** [comment]
>Test how far wound assignment can be optimized, benchmark, check if extension is necessary

#8926 optimized a bit. Going back to extension seems problematic now that we support 3rd party wound handling, though.

**Comment by jonpas** [comment]
There is no need for the extension if performance in SQF is good. Some benchmarks would be nice, maybe compared to the old version with extension (if it still works with today's Arma).
