### ISSUE TITLE
Medical Rewrite: Limping & fractures TODO

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/ACE3#6940]
Implement 3 level setting:
- [ ] Disabled limping
- [ ] Enabled limp when you have an open wound (healable with bandage)
- [ ] Enabled limp when you have an open or closed wound (healable with the surgical kit)
- [ ] Enabled limp when wounded, enabled fractures (healable with splint)

Implement fracture effects setting:
- [ ] Splint fully heals fracture
- [ ] Splint heals fracture, but sprinting is disabled + stamina hit

**Comment by PabstMirror** [comment]
look into fnc_handleBandageOpening.sqf and openWounds

**Comment by PabstMirror** [comment]
Pain:
Should a fracture add constant pain, or maybe set a floor for constant pain experienced?

Aim Co Values:
https://github.com/acemod/ACE3/blob/master/addons/medical_engine/functions/fnc_updateDamageEffects.sqf#L33-L34
https://github.com/acemod/ACE3/blob/master/addons/medical_engine/functions/fnc_updateDamageEffects.sqf#L42-L43
` if ((_fractures select 2) == 1) then { _aimFracture = _aimFracture + 4; };`

Came up with aim coefficent additives of 4 and 2 for fractures/splints. May want to adjust these values

**Comment by Will-Nichols** [comment]
> Pain:
> Should a fracture add constant pain, or maybe set a floor for constant pain experienced?

A fracture should always have pain IF you have not added a pain reliever of some type and a splint should never be the impetus to heal a fracture completely. Just like a splint should not allow anything more than a limping while walking. Having a splint allow a player to run is not the right way to do it via advanced medical.
